### ISSUE TITLE
Rendered content contains not sanitized HTML tags 

### ISSUE THREAD

**Issue by emsyzz** [contentful/rich-text.php#34]
HTML tags inserted as text in Contentful's WYSIWYG is not sanitized on rendering.

**Comment by pgrigoruta** [comment]
Good find @emsyzz , thanks for sharing! We have fixed this issue at https://github.com/contentful/rich-text.php/commit/2cd380eeb43b2bc7aa93eaf7aee0c9de19b0bd4f
