### ISSUE TITLE
How to parse markdown field

### ISSUE THREAD

**Issue by zenonyip** [contentful/rich-text.php#42]
if i set a long text field as markdown,how to parse this to html?

**Comment by pgrigoruta** [comment]
Hi @zenonyip , check https://github.com/contentful/rich-text.php#rendering , using the Renderer should to the trick:

`$entry = $client->getEntry('ENTRY_ID');
$renderer = new \Contentful\RichText\Renderer();
echo $renderer->render($entry->get('FIELD_NAE'));`
