### ISSUE TITLE
LinkResolverInterface

### ISSUE THREAD

**Issue by ray-itech** [contentful/rich-text.php#58]
Hello, 

I am confused with what the `LinkResolverInterface` argument should be. I am following the example in https://github.com/contentful/rich-text.php#parsing

<img width="650" alt="Screenshot 2021-05-26 at 12 59 57" src="https://user-images.githubusercontent.com/63705600/119656219-5c33db80-be22-11eb-92f7-126adcf6a962.png">

Trying to parse multiple `paragraph` `nodeType`

**Comment by Sebb767** [comment]
Hi @ray-itech ,

the documentation is, unfortunately, a bit outdated at the moment. Refreshing that is on my TODO-List. For now, you can create a link resolver via:

```php
$resolver = new \Contentful\Delivery\LinkResolver($client, $client->getResourcePool());
```

where `$client` is your Delivery SDK client. You usually also don't need to parse rich text data when received via the SDK, it already does that for you.

If you're using the Management SDK, you can create a link resolver via:

```php
$resolver = new \Contentful\Management\LinkResolver($client, new \Contentful\Management\ApiConfiguration(), new \Contentful\Management\RequestUriBuilder());
``` 

In the next update I'll include a method to directly create the resolver from the client. Hope this helps!

**Comment by ray-itech** [comment]
Hello @Sebb767 ,

Thanks for the response, this helps 😃
