### ISSUE TITLE
Can't create an Entry with RichText-Field

### ISSUE THREAD

**Issue by michaelLoeffelmann** [contentful/rich-text.php#60]
I'm trying to create an new Entry with a RichText field like this:

`$text1 = new Text('TEXT1 ');
        $text2 = new Text('TEXT 2');

        $paragraph = new Paragraph([$text1, $text2]);
        $document = new Document([$paragraph]);

        $entry = new Entry('test');
        $entry->setField(
            'body',
            'en-US',
            $document,
        );

        $environmentProxy->create($entry);`

When i run this, i'll get following Error from the Contentful API:

```
{
  "sys": {
    "type": "Error",
    "id": "InvalidEntry"
  },
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "required",
        "details": "The property \"data\" is required here",
        "path": [
          "fields",
          "body",
          "zzz-AA",
          "data"
        ]
      }
    ]
  }
}
```

Whats the Problem here? I hope somebody can help me here.

**Comment by Sebb767** [comment]
I'll try to reproduce your issue :)

How does your content type look like? Or do you get these errors with any type?

**Comment by LrMiLoef** [comment]
I‘ll geht this error with every content types. 😉

**Comment by Raymond-Ly** [comment]
Hello, you are missing the `data` property which is required for all RichText Nodes:

<img width="467" alt="Screenshot 2022-06-24 at 20 45 38" src="https://user-images.githubusercontent.com/63705600/175657281-0876ff87-6cba-4bf4-87c4-e41ca5ced0a8.png">
