### ISSUE TITLE
table-header-cell not support in the latest version

### ISSUE THREAD

**Issue by brightq** [contentful/rich-text.php#62]
When adding a new table element on the richtext, 

If I enable table header, the code throw out the following errors. 

Unrecognized node type "table-header-cell" when trying to parse rich text.

Works when disable the header cell 
![image](https://user-images.githubusercontent.com/3533280/177093491-e42f9f28-dc10-4b7e-a0e4-80d33654c1b9.png)

**Comment by brightq** [comment]
pull request created https://github.com/contentful/rich-text.php/pull/63

**Comment by Sebb767** [comment]
PR is merged and will be released right now :)
